In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
%matplotlib
%config InlineBackend.figure_formats=set(['retina'])

Using matplotlib backend: Qt5Agg


In [7]:
a=np.loadtxt('test_s.txt')
b=np.loadtxt('test_r.txt')
c=np.loadtxt('test_d.txt')
print(a,b,c)

[[ 5.          5.5                nan ...         nan         nan
          nan]
 [ 5.          5.5                nan ...         nan         nan
          nan]
 [ 5.          5.5                nan ...         nan         nan
          nan]
 ...
 [ 5.0001      5.5001     -0.75128798 ... -1.09096829  0.36172105
  35.63515636]
 [ 5.0001      5.5001     -0.7514861  ... -1.09111026  0.36171827
  35.63927565]
 [ 5.0001      5.5001     -0.75168441 ... -1.09125238  0.36171549
  35.64339887]] [[ 4.          4.5        -0.63700518 ... -1.01536161  0.36176754
  33.34737225]
 [ 4.001       4.501      -0.63700177 ... -1.0153528   0.36177535
  33.34731151]
 [ 4.002       4.502      -0.6369984  ... -1.01534401  0.36178312
  33.34725031]
 ...
 [ 6.397       6.897      -0.63524644 ... -1.01243722  0.36424321
  33.27429783]
 [ 6.398       6.898      -0.63524655 ... -1.01243672  0.36424367
  33.27428954]
 [ 6.399       6.899      -0.63524665 ... -1.01243622  0.36424412
  33.27428124]] [[ 3.5         4

In [3]:
plt.figure()
for i in range(a.shape[0]-1):
    plt.plot(a[0,:],a[i+1,:],label=i)
plt.grid()
plt.show()

In [35]:
plt.figure()
plt.plot(np.arange(a.size)*0.01,a)
plt.grid()
plt.show()

In [8]:
plt.figure()
for i in range(a.shape[1]-3):
    plt.plot(np.arange(a.shape[0])*1e-3, a[:,i+2],label=("l={}".format(i)))
#plt.yscale('symlog', linthresy=0.0001)
plt.grid(True)
plt.legend()
plt.show()

In [13]:
#differences in log
for i in range(a.shape[0]):
    if not np.isnan(a[i,2]):
        t=i
        break
plt.figure()
for i in range(a.shape[1]-3):
    plt.semilogy(np.arange(a.shape[0])*1e-3-0.31, a[t,i+2]-a[:,i+2],label=("l={}".format(i)))
#plt.yscale('symlog', linthresy=1e-5)
plt.grid(True)
plt.legend()
plt.show()
t

3098

In [53]:
plt.figure()
for i in range(b.shape[1]-2):
    plt.semilogy(4+np.arange(b.shape[0])*1e-3-6.5,b[-1,i+2]- b[:,i+2],label=("l={}".format(i)))
plt.grid()
plt.legend()
plt.show()

In [13]:
plt.figure()
for i in range(c.shape[1]-3):
    plt.plot(c[:,1]-c[:,0], c[:,i+2],label=("l={}".format(i)))
plt.grid()
plt.legend()
plt.show()

In [60]:
a.shape

(1000, 10)

In [63]:
wf=np.loadtxt('output.txt')
wf

array([[0.35      , 0.3501    , 0.3502    , ..., 6.9997    , 6.9998    ,
        6.9999    ],
       [0.        , 0.        , 0.        , ..., 0.17818857, 0.17822525,
        0.17826192]])

In [64]:
plt.figure()
plt.plot(wf[0], wf[1])
plt.grid()
plt.show()

In [59]:
e=np.loadtxt('test_e.txt')
e

array([[ 0.00000000e+00,             nan,             nan, ...,
                    nan,             nan,             nan],
       [ 1.00000000e-04,  1.67204396e-02,  3.75189745e-04, ...,
        -0.00000000e+00, -0.00000000e+00,  1.23696667e+00],
       [ 2.00000000e-04,  2.21034342e-02,  1.05274302e-03, ...,
         0.00000000e+00,  0.00000000e+00,  1.08645645e+00],
       ...,
       [ 5.93000000e-01,  1.04444552e+00, -7.50868009e-01, ...,
         2.13976802e-02,  1.48104605e-02,  3.43381606e+01],
       [ 5.93100000e-01,  1.04403829e+00, -7.51260633e-01, ...,
         2.14052627e-02,  1.48153388e-02,  3.43371285e+01],
       [ 5.93200000e-01,  1.04363111e+00, -7.51653216e-01, ...,
         2.14128478e-02,  1.48202178e-02,  3.43360985e+01]])

In [60]:
plt.figure()
for i in range(e.shape[1]-2):
    plt.plot(e[:,0], (2*(i)+1)*np.sin(e[:,i+1])**2, label=('l = {}'.format(i)))
plt.plot(e[:,0], e[:,16], label=('$\sigma_{tot}$'))
plt.grid()
plt.legend()
plt.show()

In [32]:
a[0,2]

nan

In [12]:
bessel=np.loadtxt('test_b.txt')
bessel

array([[ 0.00000000e+00,             nan,             nan, ...,
                    nan,             nan,             nan],
       [ 1.00000000e-04,  3.33333360e-05,  3.33333340e-05, ...,
        -1.50000000e+17, -1.50000000e+17, -3.20000000e+01],
       [ 2.00000000e-04,  6.66666660e-05,  6.66666660e-05, ...,
        -9.37500004e+15, -9.37500004e+15, -4.00000000e+00],
       ...,
       [ 6.99970000e+00, -9.43286685e-02, -9.43286685e-02, ...,
         1.52736584e-01,  1.52736584e-01,  0.00000000e+00],
       [ 6.99980000e+00, -9.43165903e-02, -9.43165903e-02, ...,
         1.52733947e-01,  1.52733947e-01,  0.00000000e+00],
       [ 6.99990000e+00, -9.43045116e-02, -9.43045116e-02, ...,
         1.52731310e-01,  1.52731310e-01,  0.00000000e+00]])

In [21]:
berr=np.array([bessel[:,i] for i in range(19) if i%3==0])
plt.figure()
for i in range(berr.shape[0]-1):
    plt.plot(berr[0,:], np.abs(berr[i+1,:]), label='{}'.format(i))
plt.yscale('symlog', lintreshold=1e-12)
plt.legend()
plt.grid()
plt.show()

/home/filippo/anaconda3/lib/python3.7/site-packages/ipykernel/eventloops.py:106: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  app.exec_()


In [10]:
berr=np.array([bessel[:,i] for i in range(19) if i%3!=0])
plt.figure()
for i in range(berr.shape[0]):
    plt.plot(bessel[:,0], berr[i,:], label='{}'.format(i))
plt.legend()
plt.grid()
plt.show()

/home/filippo/anaconda3/lib/python3.7/site-packages/ipykernel/eventloops.py:106: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  app.exec_()


In [19]:
print(berr[1])

[   nan 2.e-12 0.e+00 ... 0.e+00 0.e+00 0.e+00]
