In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
%matplotlib
%config InlineBackend.figure_formats=set(['retina'])

Using matplotlib backend: Qt5Agg


In [48]:
a=np.loadtxt('test_s.txt', dtype=float)
b=np.loadtxt('test_r.txt')
c=np.loadtxt('test_d.txt')
print(a,b,c)

[[ 5.          5.5                nan ...         nan         nan
          nan]
 [ 5.          5.5                nan ...         nan         nan
          nan]
 [ 5.          5.5                nan ...         nan         nan
          nan]
 ...
 [ 5.          5.5        -0.74581824 ... -1.08705677  0.36179762
  35.52141874]
 [ 5.          5.5        -0.74775457 ... -1.08843976  0.36177042
  35.56168228]
 [ 5.          5.5        -0.74971004 ... -1.08983836  0.36174297
  35.6023428 ]] [[ 4.          4.5        -0.63700518 ... -1.01536161  0.36176754
  33.34737224]
 [ 4.01        4.51       -0.63697263 ... -1.01527425  0.36184427
  33.34674411]
 [ 4.02        4.52       -0.63694339 ... -1.01518858  0.36191808
  33.34607056]
 ...
 [ 6.37        6.87       -0.63524374 ... -1.01245143  0.36423029
  33.27451499]
 [ 6.38        6.88       -0.63524471 ... -1.01244604  0.36423523
  33.27443613]
 [ 6.39        6.89       -0.63524572 ... -1.0124408   0.36423999
  33.27435539]] [[ 3.5         4

In [135]:
plt.figure()
for i in range(a.shape[0]-1):
    plt.plot(a[0,:],a[i+1,:],label=i)
plt.grid()
plt.show()

In [217]:
aa=np.array([1, 'nan', 2, np.nan, 3], dtype=float)
aa[aa is not 'nan' and aa>2]+=10
aa

/home/filippo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


array([ 1., nan,  2., nan, 13.])

In [49]:
a[np.greater(a,1.5,where=~np.isnan(a))]-=np.pi
#a[a>1.5]-=np.pi
plt.figure()
for i in range(a.shape[1]-3):
    plt.plot(np.arange(a.shape[0])*1e-3, a[:,i+2],label=("l={}".format(i)))
#plt.yscale('symlog', linthresy=0.0001)
plt.grid(True)
plt.legend()
plt.show()

In [50]:
#differences in log
for i in range(a.shape[0]):
    if not np.isnan(a[i,2]):
        t=i
        break
a[a==0]=np.nan
plt.figure()
for i in range(a.shape[1]-3):
    eghe=np.abs(a[t,i+2]-a[:,i+2])
    eghe[eghe==0]=np.nan
    plt.semilogy(np.arange(a.shape[0])*1e-3-0.31,eghe,label=("l={}".format(i)))
#plt.yscale('symlog', linthresy=1e-5)
plt.grid(True)
plt.legend()
plt.show()
t

310

In [56]:
plt.figure()
for i in range(b.shape[1]-3):
    plt.plot(4+np.arange(b.shape[0])*1e-2,b[:,i+2],label=("l={}".format(i)))
plt.grid()
plt.legend()
plt.show()

In [70]:
plt.figure()
for i in range(b.shape[1]-3):
    plt.semilogy(4+np.arange(b.shape[0])*1e-2-6.5,np.abs(b[0,i+2]- b[:,i+2]),label=("l={}".format(i)))
plt.grid()
plt.legend()
plt.show()

In [59]:
plt.figure()
for i in range(c.shape[1]-3):
    plt.plot(c[:,1]-c[:,0], c[:,i+2],label=("l={}".format(i)))
plt.grid()
plt.legend()
plt.show()

In [60]:
a.shape

(1000, 10)

In [63]:
wf=np.loadtxt('output.txt')
wf

array([[0.35      , 0.3501    , 0.3502    , ..., 6.9997    , 6.9998    ,
        6.9999    ],
       [0.        , 0.        , 0.        , ..., 0.17818857, 0.17822525,
        0.17826192]])

In [64]:
plt.figure()
plt.plot(wf[0], wf[1])
plt.grid()
plt.show()

In [37]:
e=np.loadtxt('test_e.txt')
e

array([[ 0.00000000e+00,             nan,             nan, ...,
                    nan,             nan,             nan],
       [ 1.00000000e-03,  2.49578317e-02,  1.10048663e-02, ...,
        -0.00000000e+00, -0.00000000e+00,  4.35755465e-01],
       [ 2.00000000e-03,  5.53391871e-04,  2.84014392e-02, ...,
         0.00000000e+00,  0.00000000e+00,  5.35725607e-01],
       ...,
       [ 5.91000000e-01,  1.05259911e+00, -7.43007126e-01, ...,
         2.12465654e-02,  1.47130246e-02,  3.43592332e+01],
       [ 5.92000000e-01,  1.04852014e+00, -7.46939573e-01, ...,
         2.13219951e-02,  1.47617121e-02,  3.43485938e+01],
       [ 5.93000000e-01,  1.04444552e+00, -7.50868009e-01, ...,
         2.13976802e-02,  1.48104605e-02,  3.43381606e+01]])

In [38]:
plt.figure()
for i in range(e.shape[1]-2):
    plt.plot(e[:,0], (2*(i)+1)*np.sin(e[:,i+1])**2, label=('l = {}'.format(i)))
plt.plot(e[:,0], e[:,16], label=('$\sigma_{tot}$'))
plt.grid()
plt.legend()
plt.show()

In [32]:
a[0,2]

nan

In [13]:
bessel=np.loadtxt('test_b.txt')
bessel

array([[ 0.00000000e+00,             nan,             nan, ...,
                    nan,             nan,             nan],
       [ 1.00000000e-03,  3.33333300e-04,  3.33333300e-04, ...,
        -1.50000015e+13, -1.50000015e+13,  0.00000000e+00],
       [ 2.00000000e-03,  6.66666400e-04,  6.66666400e-04, ...,
        -9.37500375e+11, -9.37500375e+11, -1.22070312e-04],
       ...,
       [ 6.99700000e+00, -9.46545678e-02, -9.46545678e-02, ...,
         1.52807358e-01,  1.52807358e-01,  0.00000000e+00],
       [ 6.99800000e+00, -9.45339121e-02, -9.45339121e-02, ...,
         1.52781237e-01,  1.52781237e-01, -2.77600000e-17],
       [ 6.99900000e+00, -9.44132002e-02, -9.44132002e-02, ...,
         1.52755008e-01,  1.52755008e-01,  2.77600000e-17]])

In [42]:
berr=np.array([bessel[:,i] for i in range(19) if i%3==0])
berr[berr==0]=np.nan
plt.figure()
for i in range(berr.shape[0]-1):
    kekko=np.isfinite(berr[i+1,:])
    plt.loglog(berr[0,kekko], np.abs(berr[i+1,kekko]),  label='{}'.format(i))
#plt.yscale('symlog', lintreshold=1e-12)
plt.legend()
plt.grid()
plt.show()

The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.


In [44]:
berr=np.array([bessel[:,i] for i in range(19) if (i-1)%3==0])
plt.figure()
for i in range(berr.shape[0]):
    plt.plot(bessel[:,0], berr[i,:], label='{}'.format(i))
plt.legend()
plt.grid()
plt.show()

The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.


In [40]:
a=np.array([[0,1,2,3], [0,1,2,3]], dtype=float)
a[a==0]=np.nan
kkk=np.isfinite(a[1])
a[:,kkk]

array([[1., 2., 3.],
       [1., 2., 3.]])

In [60]:
name='/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax7_eo.txt'
errori_maurat=np.loadtxt(name)
errori_maurat = np.abs(errori_maurat-np.array([0, 0.5, 1.5, 2.5, 3.5, 4.5]))
errori_maurat

array([[1.00000000e-01, 3.91168192e-07, 2.73927102e-06, 9.78796533e-06,
        2.46797826e-05, 5.05661206e-05],
       [7.00000000e-02, 9.38529317e-08, 6.57098655e-07, 2.34734908e-06,
        5.91696899e-06, 1.21185374e-05],
       [4.65500000e-02, 1.83471786e-08, 1.28441367e-07, 4.58768179e-07,
        1.15623796e-06, 2.36784976e-06],
       [3.20000000e-02, 4.09655698e-09, 2.86771442e-08, 1.02423887e-07,
        2.58123166e-07, 5.28571108e-07],
       [2.16700000e-02, 8.61486105e-10, 6.03017680e-09, 2.15367972e-08,
        5.42742948e-08, 1.11136285e-07],
       [1.47800000e-02, 1.86427984e-10, 1.30483846e-09, 4.66037120e-09,
        1.17443046e-08, 2.40480498e-08],
       [1.00000000e-02, 3.91101596e-11, 2.73506107e-10, 9.76693837e-10,
        2.46044962e-09, 5.03920372e-09],
       [6.90000000e-03, 8.79585293e-12, 6.18016749e-11, 2.21409113e-10,
        5.57869306e-10, 1.14237508e-09],
       [4.50000000e-03, 1.84413596e-12, 1.12303500e-11, 3.98805433e-11,
        1.01122222e-10, 

In [61]:
print(np.polyfit(np.log(errori_maurat[:10,0]), np.log(errori_maurat[:10,1:]),1))
colors=['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan']
plt.figure()
for i in range(errori_maurat.shape[1]-1):
    m,q = np.polyfit(np.log(errori_maurat[:10,0]), np.log(errori_maurat[:10,i+1]),1)
    plt.loglog(errori_maurat[:,0], errori_maurat[:,0]**m*np.exp(q),'--', color=colors[i], linewidth=2, alpha=.5)
    plt.loglog(errori_maurat[:,0], errori_maurat[:,i+1], color=colors[i], label='E = {}'.format(0.5+i))
plt.title(name)
plt.grid()
plt.legend()
plt.show()

[[ 3.89113698  3.98258413  4.0126953   4.00105688  3.99969794]
 [-5.9026411  -3.65641709 -2.28353789 -1.39753306 -0.68519897]]


In [321]:
names=['/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax6_eo.txt',
      '/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax7_eo.txt',
      '/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax8.5_eo.txt',
      '/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax10_eo.txt']
nu=np.array([np.abs(np.loadtxt(names[i], usecols=(0,5))-np.array([0,0.5+4])) for i in range(4)])
#nu

In [322]:
#print(np.polyfit(np.log(errori_maurat[:10,0]), np.log(errori_maurat[:10,1:]),1))
colors=['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan']
plt.figure()
for i in range(nu.shape[0]):
    #m,q = np.polyfit(np.log(errori_maurat[:10,0]), np.log(errori_maurat[:10,i+1]),1)
    #plt.loglog(nu[i,:,0], errori_maurat[:,0]**m*np.exp(q),'--', color=colors[i], linewidth=2, alpha=.5)
    plt.loglog(nu[i,:,0], nu[i,:,1], color=colors[i], label='$r_{max}$ =')

plt.grid()
plt.legend()
plt.show()

In [274]:
names=['/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax7_eo.txt',
      '/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax7_eo.txt',
      '/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax8.5_eo.txt',
      '/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax10_eo.txt']
tu=np.array([np.abs(np.loadtxt(names[0], usecols=(0,1))-np.array([0,np.loadtxt(names[i+1], usecols=(1))])) for i in range(3)])
tu.shape

(3, 20, 2)

In [275]:
#print(np.polyfit(np.log(errori_maurat[:10,0]), np.log(errori_maurat[:10,1:]),1))
colors=['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan']
plt.figure()
for i in range(tu.shape[0]):
    #m,q = np.polyfit(np.log(errori_maurat[:10,0]), np.log(errori_maurat[:10,i+1]),1)
    #plt.loglog(nu[i,:,0], errori_maurat[:,0]**m*np.exp(q),'--', color=colors[i], linewidth=2, alpha=.5)
    plt.loglog(tu[i,:,0], tu[i,:,1], color=colors[i], label='$r_{max}$ =')

plt.grid()
plt.legend()
plt.show()

ValueError: setting an array element with a sequence.

In [273]:
np.array([0,np.loadtxt(names[i+1], usecols=(1))])

array([0,
       array([1.49999961, 1.49999991, 1.49999998, 1.5       , 1.5       ,
       1.5       , 1.5       , 1.5       , 1.5       , 1.5       ,
       1.5       , 1.5       , 1.5       , 1.5       , 1.5       ,
       1.5       , 1.5       , 1.5       , 1.5       , 1.5       ])],
      dtype=object)

In [308]:


tu

array([3.33066907e-16, 4.44089210e-16, 2.22044605e-16, 3.33066907e-16,
       3.88578059e-16, 6.66133815e-16, 2.77555756e-16, 5.55111512e-17,
       3.33066907e-16, 3.33066907e-16, 2.77555756e-16, 0.00000000e+00,
       1.66533454e-16, 1.11022302e-16, 4.44089210e-16, 3.33066907e-16,
       3.33066907e-16, 4.44089210e-16, 1.66533454e-16, 1.66533454e-16])

In [315]:
#print(np.polyfit(np.log(errori_maurat[:10,0]), np.log(errori_maurat[:10,1:]),1))
colors=['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan']
plt.figure()

uuu=np.loadtxt('/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-11_h_rmax8.5_eo.txt')
iii=np.loadtxt('/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-11_h_rmax10_eo.txt')
tu = np.abs(uuu[:,1]-iii[:,1])

plt.loglog(uuu[:,0], tu, color=colors[0], label=r'$E_{threshold} = 10^{-11}$')

uuu=np.loadtxt('/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax8.5_eo.txt')
iii=np.loadtxt('/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-13_h_rmax10_eo.txt')
tu = np.abs(uuu[:,1]-iii[:,1])

plt.loglog(uuu[:,0], tu, color=colors[1], label=r'$E_{threshold} = 10^{-13}$')

uuu=np.loadtxt('/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-15_h_rmax8.5_ground.txt')
iii=np.loadtxt('/home/filippo/Desktop/Computazionale/Project_1/Mauro/HO1DE_1e-15_h_rmax10_ground.txt')
tu = np.abs(uuu[:,1]-iii[:,1])

plt.loglog(uuu[:,0], tu, color=colors[2], label=r'$E_{threshold} = 10^{-15}$')

plt.grid()
plt.legend()
plt.show()

In [353]:
plt.figure(7)
plt.grid(True, which='major', axis='both')
plt.show()